name: Build and Release

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0.0

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-gnu]

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename and package
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/kanban dist/kanban-${{ matrix.target }}

      - uses: actions/upload-artifact@v3
        with:
          name: kanban-${{ matrix.target }}
          path: dist/kanban-${{ matrix.target }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/kanban-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
