name: Release

on:
  push:
    tags:
      - "v*" # Matches tags like v1.0.0

jobs:
  release:
    name: Build and Package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows
            ext: .exe
          - target: x86_64-unknown-linux-gnu # Changed from musl for .deb compatibility
            os: linux
            ext:
          - target: x86_64-apple-darwin
            os: macos
            ext:

    steps:
      - uses: actions/checkout@v3

      # Install Rust and target
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      # Install Linux dependencies for .deb creation
      - name: Install deb dependencies
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y debhelper dh-make devscripts fakeroot

      # Build the release binary
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      # Get version from tag
      - name: Get version
        id: get_version
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      # Package for Linux (.deb)
      - name: Create .deb package
        if: matrix.os == 'linux'
        run: |
          mkdir -p debian/usr/bin
          cp target/${{ matrix.target }}/release/your-binary-name debian/usr/bin/
          mkdir -p debian/DEBIAN
          cat > debian/DEBIAN/control <<EOF
          Package: your-binary-name
          Version: ${{ steps.get_version.outputs.version }}
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <your.email@example.com>
          Description: Your application description
          EOF
          dpkg-deb --build debian your-binary-name_${{ steps.get_version.outputs.version }}_amd64.deb

      # Prepare artifacts
      - name: Prepare artifacts
        run: |
          mkdir artifacts
          if [ "${{ matrix.os }}" = "linux" ]; then
            cp your-binary-name_${{ steps.get_version.outputs.version }}_amd64.deb artifacts/
          fi
          cp target/${{ matrix.target }}/release/your-binary-name${{ matrix.ext }} artifacts/your-binary-name-${{ matrix.target }}${{ matrix.ext }}

      # Create release and upload artifacts
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
