name: Build Linux .deb

on:
  push:
    tags:
      - "v*" # Matches tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install build tools
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            debhelper dh-make \
            devscripts fakeroot

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Build release binary
      - name: Build
        run: cargo build --release

      # Get version from tag (removes 'v' prefix if present)
      - name: Get version
        id: get_version
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      # Create .deb package
      - name: Create Debian package
        run: |
          BINARY_NAME="kanban"  # CHANGE THIS to your binary name from Cargo.toml
          mkdir -p debian/usr/bin
          cp target/release/$BINARY_NAME debian/usr/bin/

          mkdir -p debian/DEBIAN
          cat > debian/DEBIAN/control <<EOF
          Package: $BINARY_NAME
          Version: ${{ steps.get_version.outputs.version }}
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <your@email.com>
          Description: Your application description
          EOF

          dpkg-deb --build debian ${BINARY_NAME}_${{ steps.get_version.outputs.version }}_amd64.deb

      # Upload artifact
      - name: Upload .deb package
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: |
            *.deb
